### ISSUE TITLE
Missing loader after updating sanity

### ISSUE THREAD

**Issue by PaulPCIO** [sanity-io/sanity-plugin-graph-view#4]
I just updated the sanity studio using `sanity upgrade` and since the update I can no longer run with the graph-view enabled

![image](https://user-images.githubusercontent.com/39598117/122835378-bfa91000-d2df-11eb-88fc-bf8649596acb.png)

**Comment by evenwestvang** [comment]
Thank you for letting us know Paul!

**Comment by 3200pro** [comment]
Same here. Shuts down launching the studio unless the plugin is uninstalled.

**Comment by AaronBentley** [comment]
Me too, we find this plugin super handy for monitoring our content ♥️

**Comment by atombender** [comment]
We're looking into this!

**Comment by atombender** [comment]
The cause is that Three.js has decided to use non-standard JavaScript syntax, which Sanity does not transpile out of the box. In our experience, this is pretty uncommon among Node.js modules that are to be used in the browser, and it makes it difficult to support Three.js in Sanity, which assumes all Node.js modules are browser-compatible.

We have released a fix as `v1.0.7`. Unfortunately, this fix relies on a feature of Yarn to pin a deep dependency to a specific version; as far as I know, there's no equivalent solution for NPM. So for now, you have to use Yarn to manage your app's modules.

I'll close this issue for now, but we will hopefully find a more permanent fix at some point.

**Comment by XSlemX** [comment]
Still not working for me with these versions(brand new project):
![image](https://user-images.githubusercontent.com/10440356/124364064-6033f400-dc3f-11eb-9055-fc662d16a1e9.png)

**Comment by atombender** [comment]
Unfortunately, you're right. You have to add the following to your app's `package.json`:

```json
  "resolutions": {
    "**/three": "0.119.1"
  }
```

Unfortunately, this workaround _only_ works with Yarn, not NPM. There's no current workaround for NPM.

I've amended the readme.
